export enum StockItemTransactionType {
  Initial = 0,
  Purchase = 1,
  PurchaseReturn = 2,
  Sale = 3,
  SaleReturn = 4,
  StocktakePlus = 5,
  StocktakeMinus = 6,
  Damage = 7,
  Loss = 8,
  Steal = 9,
  StockTransferMinus = 10,
  StockTransferPlus = 11,
  DelistedSaleReturn = 14,
}
