import { ErrorCode } from '../../enums/error-codes.enum';

export const IDENTITY_EXCEPTIONS = {
  [ErrorCode.DefaultError]: 'დაფიქსირდა შეცდომა',
  [ErrorCode.ConcurrencyFailure]: 'Concurrency Failure',
  [ErrorCode.PasswordMismatch]: 'პაროლი არ ემთხვევა',
  [ErrorCode.InvalidToken]: 'არასწორია ტოკენი',
  [ErrorCode.LoginAlreadyAssociated]: 'Login Already Associated',
  [ErrorCode.InvalidUserName]: 'მომხმარებელი არასწორია',
  [ErrorCode.InvalidEmail]: 'ელ. ფოსტა არასწორია',
  [ErrorCode.DuplicateUserName]: 'Duplicated User Name',
  [ErrorCode.DuplicateEmail]: 'Duplicated Email',
  [ErrorCode.InvalidRoleName]: 'Invalid Role Name',
  [ErrorCode.DuplicateRoleName]: 'Duplicated Role Name',
  [ErrorCode.UserAlreadyHasPassword]: 'User Already Has Password',
  [ErrorCode.UserLockoutNotEnabled]: 'User Lockout Not Enabled',
  [ErrorCode.UserAlreadyInRole]: 'User Already In Role',
  [ErrorCode.UserNotInRole]: 'User Not In Role',
  [ErrorCode.PasswordTooShort]: 'Password Too Short',
  [ErrorCode.PasswordRequiresNonAlphanumeric]: 'Password Requires Non Alphanumeric',
  [ErrorCode.PasswordRequiresDigit]: 'Password Requires Digit',
  [ErrorCode.PasswordRequiresLower]: 'Password Requires Lower',
  [ErrorCode.PasswordRequiresUpper]: 'Password Requires Upper',
  [ErrorCode.InvalidPhoneNumber]: 'ტელეფონის ნომერი არასწორია',
  [ErrorCode.InvalidCredentials]: 'თქვენ მიერ შეყვანილი მომხმარებელი და პაროლი არცერთ ანგარიშს არ შეესაბამება',
  [ErrorCode.RefreshTokenUsed]: 'Refresh Token Used',
  [ErrorCode.UserExists]: 'მომხმარებელი უკვე არსებობს',
  [ErrorCode.UserVerificationPending]: 'ვერიფიკაცია პროცესშია',
  [ErrorCode.RefreshTokenNotFound]: 'Refresh Token Not Found',
  [ErrorCode.UserNotFound]: 'მომხმარებელი არ მოიძებნა',
  [ErrorCode.NotificationNotSent]: 'Notification Not Sent',
  [ErrorCode.AlreadyRegisteredException]: 'Already Registered Exception',
  [ErrorCode.UserLockedOut]: 'მომხმარებელი დროებით დაიბლოკა',
  [ErrorCode.IdentificationNumberExists]: 'საიდენტიფიკაციო ნომერი უკვე არსებობს',
  [ErrorCode.NoActiveLegalEntitiesException]: 'NoActiveLegalEntitiesException',
  [ErrorCode.LegalEntitySuspendedException]: 'LegalEntitySuspendedException ',
  [ErrorCode.NotificationPhoneNumberRequired]: 'ტელეფონის ნომერი აუცილებელია',
  [ErrorCode.NotificationOtpRequired]: 'ერთჯერადი პაროლი აუცილებელია',
  [ErrorCode.NotificationInvalidPhoneNumber]: 'Invalid PhoneNumber',
  [ErrorCode.NotificationOtpLimitExhausted]: 'გთხოვთ დაელოდეთ',
  [ErrorCode.NotificationOtpExpired]: 'ერთჯერად პაროლს გაუვიდა ვადა',
  [ErrorCode.NotificationOtpUsed]: 'ერთჯერადი პაროლი უკვე გამოყენებულია',
  [ErrorCode.NotificationWrongOtp]: 'ერთჯერადი პაროლი არასწორია'
};
